[package]
name = "pycors"
version = "0.1.11"
authors = ["Nicolas Bigaouette <nbigaouette@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
console = "0.7"
chrono = "0.4"
dirs = "1.0"
env_logger = "0.6"
failure = "0.1"
flate2 = "1.0"
human-panic = "1.0"
indicatif = "0.11"
log = "0.4"
prettytable-rs = "0.8"
question = "0.2"
regex = "1.1"
reqwest = "0.9"
semver = "0.9"
structopt = "0.2"
subprocess = "0.1"
tar = "0.4"
terminal_size = "0.1"
url = "1.7"
shlex = "0.1"
which = "2.0"

[build-dependencies]
# git-version = "0.2"
git-version = { git = "https://github.com/m-ou-se/rust-git-version.git", rev = "8b80be8ac15e017529a9d6e2195b348ff712617e" }
