[package]
name = "pycors"
version = "0.0.2"
authors = ["Nicolas Bigaouette <nbigaouette@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0"
env_logger = "0.6"
failure = "0.1"
indicatif = "0.11"
log = "0.4"
prettytable-rs = "0.8"
reqwest = "0.9"
semver = { version = "0.9", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
structopt = "0.2"
toml = "0.4"
url = "1.7"
