name: "Nightly audit"

on: [push]
# on:
#   schedule:
#     - cron:  '0 0 * * *'

jobs:
  nightly-audit:
    name: "Nightly audit"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

        # See https://github.com/embarkstudios/cargo-deny
      - name: Install 'cargo-deny'
        run: |
          curl -L "https://github.com/EmbarkStudios/cargo-deny/releases/download/0.5.2/cargo-deny-0.5.2-x86_64-unknown-linux-musl.tar.gz" | tar -zxv
          mv *-x86_64-*/cargo-* $CARGO_HOME/bin/
          rm -fr *-x86_64-*
          cargo deny --help

      - name: Print licenses (cargo deny)
        run: cargo deny list

      - name: Verify advisories (cargo deny)
        run: cargo deny check advisories
